name: Feature Request
description: Suggest an improvement to the project
title: "Feature: [SHORT DESCRIPTION]"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion! We appreciate ideas to improve the project.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful? What problem does it solve?

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples
